export const dom = {
input: document.querySelector(".input"),
b: document.querySelector(".b"),
calender: document.querySelector(".calender"),
monthYear: document.querySelector(".monthyear"),
dates: document.querySelector(".dates"),
buttons: document.querySelectorAll(".navigation span"),
cardTitleL: document.querySelector(".card-title"),
cardTitleT: document.querySelector(".card-back"),
desc: document.querySelector(".card-descriptionB"),
card: document.querySelector("#card-wrapper"),
1: document.querySelector("#one"),
2: document.querySelector("#two"),
3: document.querySelector("#three"),
}